"""initial migration

Revision ID: 0de65b4133bd
Revises: 8c4107abf034
Create Date: 2026-08-06 18:21:24.108547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de65b4133bd'
down_revision: Union[str, Sequence[str], None] = '8c4107abf034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_mappings', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('url_mappings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_mappings', 'updated_at')
    op.drop_column('url_mappings', 'expires_at')
    # ### end Alembic commands ###
